const constants = {
  roles: ["EMPLOYEE", "HR"],
  gender: ["MALE", "FEMALE", "NO_ANSWER"],
  state: [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
  ],
  immigrationStatus: ["CITIZEN", "PR", "VISA"],
  applicationStatus: ["NOT_STARTED", "PENDING", "REJECTED", "APPROVED"],
  documentStatus: ["PENDING", "APPROVED", "REJECTED"],
  facilityReportStatus: ["Open", "In Progress", "Closed"],
  registrationLinkStatus: ["Used", "Not Used"],
};

export default constants;
